swagger: '2.0'
info:
  version: '1.0.0'
  title: Employee API
  description: A simple API to manage employees
paths:
  /employees:
    get:
      summary: Returns a list of all employees
      responses:
        '200':
          description: A JSON array of employees
          schema:
            type: array
            items:
              $ref: '#/definitions/Employee'
    post:
      summary: Creates a new employee
      parameters:
        - in: body
          name: employee
          description: The employee to create
          schema:
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: The created employee
          schema:
            $ref: '#/definitions/Employee'
        '400':
          description: 'Invalid input, object invalid'
  /employees/{id}:
    get:
      summary: Returns a specific employee
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: A single employee
          schema:
            $ref: '#/definitions/Employee'
        '404':
          description: 'Employee not found'
definitions:
  Employee:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      position:
        type: string
    required:
      - id
      - name
      - position